package com.aistudyhub.backend.entity;

/**
 * Represents the role of a message in a chat session.
 * USER  - message sent by the human user.
 * ASSISTANT - message generated by the AI.
 */
public enum ChatMessageRole {
    USER,
    ASSISTANT
}
