package com.aistudyhub.backend.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Provides pgvector-based semantic search directly from Spring Boot.
 *
 * <p>When {@code vector.store=pgvector}, the {@link SemanticSearchService} calls
 * this service instead of going through the Python AI service for vector search.
 * The Python service is still used for embedding generation during document
 * processing (upload), but search queries are handled entirely in Spring Boot.</p>
 *
 * <p>This approach is faster because it eliminates the Spring → Python → pgvector
 * round trip and queries pgvector directly from Spring via JDBC.</p>
 *
 * <p>Note: For semantic search, Spring Boot still needs to call Python to generate
 * the query embedding (since the embedding model runs in Python). So the flow is:
 * <ol>
 *   <li>Spring calls Python /embed-query to get the query vector</li>
 *   <li>Spring queries pgvector directly with the vector</li>
 * </ol>
 * OR, if we keep the existing Python semantic-search endpoint (which now routes
 * to pgvector internally), Spring just calls Python as before.</p>
 */
@Service
@Slf4j
public class PgvectorSearchService {

    private final JdbcTemplate jdbcTemplate;

    public PgvectorSearchService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Check if the pgvector database is reachable and the extension + table exist.
     */
    public boolean isAvailable() {
        try {
            jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            return true;
        } catch (Exception e) {
            log.warn("pgvector database is not reachable: {}", e.getMessage());
            return false;
        }
    }

    /**
     * Count embeddings for a specific document.
     */
    public long countEmbeddingsByDocumentId(Long documentId) {
        try {
            Long count = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM document_chunk_embeddings WHERE document_id = ?",
                    Long.class,
                    documentId
            );
            return count != null ? count : 0;
        } catch (Exception e) {
            log.warn("Failed to count embeddings for document {}: {}", documentId, e.getMessage());
            return 0;
        }
    }

    /**
     * Delete all pgvector embeddings for a specific document.
     *
     * <p>Called during reprocess to remove stale embeddings before new ones are
     * generated by the Python AI service. This prevents duplicate
     * {@code (document_id, chunk_index)} constraint violations when the new
     * chunk set differs from the old one.</p>
     *
     * @param documentId the document whose embeddings should be removed
     * @return number of rows deleted, or -1 if the operation failed
     */
    public int deleteEmbeddingsByDocumentId(Long documentId) {
        try {
            int deleted = jdbcTemplate.update(
                    "DELETE FROM document_chunk_embeddings WHERE document_id = ?",
                    documentId
            );
            log.info("Deleted {} pgvector embeddings for document ID: {}", deleted, documentId);
            return deleted;
        } catch (Exception e) {
            log.error("Failed to delete pgvector embeddings for document ID {}: {}",
                    documentId, e.getMessage(), e);
            return -1;
        }
    }

    /**
     * Search pgvector directly using a pre-computed query embedding.
     *
     * <p>Queries the {@code document_chunk_embeddings} table using cosine distance
     * ({@code <=>} operator). Returns rows ordered by similarity (highest first).</p>
     *
     * @param queryEmbedding  384-dimensional query vector as a float array.
     * @param documentId      If non-null, restrict to this document only.
     * @param documentIds     If non-null and non-empty, restrict to these document IDs.
     *                        Takes precedence over {@code documentId}.
     * @param topK            Number of results to return.
     * @return List of maps with keys: {@code documentId} (Long), {@code chunkIndex} (Integer),
     *         {@code score} (Double — cosine similarity, 1=identical).
     */
    public List<Map<String, Object>> searchByEmbedding(
            float[] queryEmbedding,
            Long documentId,
            List<Long> documentIds,
            int topK) {

        // Build pgvector literal string: '[0.1,0.2,...,0.384]'
        StringBuilder embStr = new StringBuilder("[");
        for (int i = 0; i < queryEmbedding.length; i++) {
            if (i > 0) embStr.append(",");
            embStr.append(queryEmbedding[i]);
        }
        embStr.append("]");
        String embeddingLiteral = embStr.toString();

        String sql;
        Object[] params;

        if (documentIds != null && !documentIds.isEmpty()) {
            // Build IN clause with placeholders
            String placeholders = documentIds.stream()
                    .map(id -> "?")
                    .collect(java.util.stream.Collectors.joining(","));
            sql = String.format(
                    "SELECT dce.document_id, dce.chunk_index, " +
                    "1 - (dce.embedding <=> '%s'::vector) AS score " +
                    "FROM document_chunk_embeddings dce " +
                    "JOIN documents d ON d.id = dce.document_id " +
                    "WHERE dce.document_id IN (%s) AND d.is_trashed = false " +
                    "ORDER BY dce.embedding <=> '%s'::vector " +
                    "LIMIT ?",
                    embeddingLiteral, placeholders, embeddingLiteral
            );
            Object[] idParams = documentIds.toArray();
            params = new Object[idParams.length + 1];
            System.arraycopy(idParams, 0, params, 0, idParams.length);
            params[idParams.length] = topK;

        } else if (documentId != null) {
            sql = String.format(
                    "SELECT dce.document_id, dce.chunk_index, " +
                    "1 - (dce.embedding <=> '%s'::vector) AS score " +
                    "FROM document_chunk_embeddings dce " +
                    "JOIN documents d ON d.id = dce.document_id " +
                    "WHERE dce.document_id = ? AND d.is_trashed = false " +
                    "ORDER BY dce.embedding <=> '%s'::vector " +
                    "LIMIT ?",
                    embeddingLiteral, embeddingLiteral
            );
            params = new Object[]{documentId, topK};

        } else {
            sql = String.format(
                    "SELECT dce.document_id, dce.chunk_index, " +
                    "1 - (dce.embedding <=> '%s'::vector) AS score " +
                    "FROM document_chunk_embeddings dce " +
                    "JOIN documents d ON d.id = dce.document_id " +
                    "WHERE d.is_trashed = false " +
                    "ORDER BY dce.embedding <=> '%s'::vector " +
                    "LIMIT ?",
                    embeddingLiteral, embeddingLiteral
            );
            params = new Object[]{topK};
        }

        log.info("[pgvector] Searching with embedding dim={}, documentId={}, documentIds={}, topK={}",
                queryEmbedding.length, documentId, documentIds, topK);

        try {
            List<Map<String, Object>> rows = jdbcTemplate.queryForList(sql, params);
            log.info("[pgvector] Returned {} rows.", rows.size());
            return rows;
        } catch (Exception e) {
            log.error("[pgvector] searchByEmbedding failed: {}", e.getMessage(), e);
            return List.of();
        }
    }
}

